/** Display name for docs and user-facing strings. */
export const PRODUCT_NAME = 'Ai Stack Kit';

/** Primary CLI binary (`npm install -g ai-stack-kit` → `aistack`). */
export const CLI_COMMAND = 'aistack';

/** Published npm package name (see package.json `name`). */
export const NPM_PACKAGE_NAME = 'ai-stack-kit';

/** Project-local workspace directory (skills, manifests, adapter artifacts). */
export const WORKSPACE_DOTDIR = '.aistack';

/** VS Code `settings.json` merge root for Copilot integration. */
export const VSCODE_SETTINGS_ROOT_KEY = 'aistack';

/** Frontmatter key marking files generated by this tool. */
export const GENERATED_FILE_MARKER_KEY = 'aistack';

/** Default skill catalog cache folder under cwd when unset. */
export const DEFAULT_RELATIVE_CACHE_DIR = '.cache/aistack';
