/** Display name for docs and user-facing strings. */
export const PRODUCT_NAME = 'AI Stack Kit';

/** Primary CLI binary (globals named below ship from scoped npm package). */
export const CLI_COMMAND = 'aistack';

/** Canonical scoped id on npm.pkg.github.com (must match GitHub repo owner). */
export const NPM_PACKAGE_NAME = '@deb-adarsh/ai-stack-kit';

/** Unscoped id on https://registry.npmjs.org/ (`npm pkg set name` in CI/local before npm publish). */
export const NPMJS_PACKAGE_NAME = 'ai-stack-kit';

/** Project-local workspace directory (skills, manifests, adapter artifacts). */
export const WORKSPACE_DOTDIR = '.aistack';

/** VS Code `settings.json` merge root for Copilot integration. */
export const VSCODE_SETTINGS_ROOT_KEY = 'aistack';

/** Frontmatter key marking files generated by this tool. */
export const GENERATED_FILE_MARKER_KEY = 'aistack';

/** Default skill catalog cache folder under cwd when unset. */
export const DEFAULT_RELATIVE_CACHE_DIR = '.cache/aistack';
